### ISSUE TITLE
The app does not create schema automatically for non-default databases

### ISSUE THREAD

**Issue by ShreeshaN** [wmeints/spring-multi-tenant-demo#2]

**Comment by tmbahadar** [comment]
I have the same issue. Not loading the schema for target tenants.

**Comment by Bryksin** [comment]
Yes, that is an interesting problem, how to initialise the 2nd DB from the same `schema.sql` and `data.sql`?

**Comment by wmeints** [comment]
My sample doesn't offer a solution for that. When we used this in our solution, we used separate SQL files and a powershell script to set up the tenant databases.
