### ISSUE TITLE
Getting nullpointer exception at  File[] files = Paths.get("tenants").toFile().listFiles();

### ISSUE THREAD

**Issue by RaghuThota** [wmeints/spring-multi-tenant-demo#8]
I am getting null pointer excpetin at line  File[] files = Paths.get("tenants").toFile().listFiles();  in MultitenantConfiguration.java file. Can you please explain you are getting files here?

**Comment by wmeints** [comment]
There should be a directory called `tenants` in the root folder of the app. In this directory you need to store yaml files for each tenant listing the settings for that tenant.
